settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(5cm);

pair a = (0, 2);
pair b = (-1.5, 0);
pair c = (2.5, -1);
triangle t = triangle(a,b,c);
show(t, La="", Lb="", Lc="");
pair i = incenter(triangle(a,b,c));
label("$I$", i, align=SW);
dot(i);
pair i1 = excenter(opposite(t.VA));
dot(i1);
label("$I_1$", i1, align=SW);
pair i2 = excenter(opposite(t.VB));
dot(i2);
label("$I_2$", i2, align=SE);
pair i3 = excenter(opposite(t.VC));
dot(i3);
label("$I_3$", i3, align=SW);
draw(i1 -- i2, dashed);
draw(i2 -- i3, dashed);
draw(i3 -- i1, dashed);
draw(i1 -- a, dashed);
draw(i2 -- b, dashed);
draw(i3 -- c, dashed);
point M = relpoint(line(t.VA, t.VC), 1.2);
draw(point(t.VC)-- M, 0.8*blue);
label("$M$", M, align=SW);
