settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(5cm);

pair O = (0,0);
path p = circle((0, 0), 2);
draw(p);
label("$O$", (0, 0), align=NW);
path q = circle((0, -2), 2.4);
draw((0, 2) -- (0, -2));
//draw(q, bp+0.5*red);
label("$A$", (0, -2), align=SW);
label("$P$", (0, .4), align=NW);
pair i[] = intersectionpoints(p, q);
draw(i[0] -- O);
draw(i[1] -- O);
label("$B$", i[0], align=NW);
label("$C$", i[1], align=NE);
draw(i[0] -- i[1], dashed);
pair A = (0, -2);
draw(i[0] -- A);
draw(i[1] -- A);
label("$r$", midpoint(line(i[0], A)), align=SW);
label("$r$", midpoint(line(i[1], A)), align=SE);
markangle("$\theta$", radius=10, O, A, i[0]);
markangle("$\theta$", radius=10, i[1], A, O);
markangle("$\theta$", radius=10, O, i[1], A);
label("$1$", midpoint(line(i[0], O)), align=NW);
label("$1$", midpoint(line(i[1], O)), align=NE);
draw(arccircle(i[0], (0, .4), i[1]));
