settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(8cm);

draw((-1,0) -- (2,0), EndArrow);
draw((0,-1) -- (0,3), EndArrow);
path c = circle((0,1), 1);
draw(c);
draw((0.8, 0) -- (1.25, 2));
draw((0,2) -- (1.25,2));
pair p[] = intersectionpoints(line((0.8, 0), (1.25,2)), c);
draw(p[0] -- (0, p[0].y));
draw(p[0] -- (0,0));
draw(p[0] -- (0,2));
label("$O$", (0,0), align=SW);
label("$B$", (0,2), align=NW);
label("$P$", (0,1), align=W);
label("$N$", (0,p[0].y), align=W);
label("$A$", p[0], align=E);
pair A = p[0];
pair O = (0,0);
pair B = (0,2);
pair T = (1.25, 2);
pair P = (0,1);
draw((-0.05,1) -- (0.05, 1));
markangle("$\theta$", radius=10, A,O,B);
markangle("$\theta$", radius=10, A,B,T);
markangle("$90^\circ$", radius=10, B,A,O);
label("$T$", T, align=NE);
label("$Q$", (0.8, 0), align=S);
