settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(4cm);

pair a = (0,4);
pair b = (-2,0);
pair c = (2,0);
triangle t = triangle(a,b,c);
draw(t);
path c1 = circle((-2,0), 2);
path c2 = circle((2,0), 2);
draw(c1);
draw(c2);
path c3 = circle((0,4), sqrt(20)- 2);
draw(c3);
label("$C1$", b, align=SW);
label("$C2$", c, align=SE);
label("$C3$", a, align=N);
label("$a$", midpoint(line(b, (0,0))), align=S);
label("$b$", midpoint(line(c, (0,0))), align=S);
label("$a$", midpoint(line(b, (-1.414,1.414))), align=NW);
label("$b$", midpoint(line(c, (1.414,1.414))), align=NE);
label("$c$", midpoint(line(a, (-1.414,1.414))), align=NW);
label("$c$", midpoint(line(a, (1.414,1.414))), align=NE);
line l1 = perpendicular(intersectionpoint(c1,c3), line(a, b));
line l2 = perpendicular(intersectionpoint(c2,c3), line(a, c));
line l3 = perpendicular((0,0), line(b, c));
pair o = intersectionpoint(l1,l2);
draw(intersectionpoint(c1,c3) -- o);
draw(intersectionpoint(c2,c3) -- o);
draw(intersectionpoint(c1,c2) -- o);
label("$O$", o + (0,0.3), align=N);
