settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(6cm);

pair a = (0,3);
pair b = (-1,0);
pair c = (3.5,0);
triangle t = triangle(a,b,c);
show(t);
pair cc = circumcenter(t);
pair i = incenter(t);
dot(cc);
dot(i);
draw(cc -- a);
draw(cc -- b);
draw(cc -- c);
draw(cc -- i);
line l = perpendicular(cc, line(b, c));
draw(cc -- intersectionpoint(l, line(b,c)));
line m = line(a, i);
draw(a -- intersectionpoint(m, line(b,c)));
line n = perpendicular(i, line(b, a));
draw(i -- intersectionpoint(n, line(b,a)));
markangle("$A/2$", radius=20, b,a,i);
markangle("$A/2$", radius=40, i,a,c);
label("$O$", cc, align=NE);
label("$I$", i, align=NE);
markangle("$90^\circ$", radius=10, i,intersectionpoint(n, line(b,a)),a);
label("$M$", intersectionpoint(l, line(b,c)), align=SW);
label("$D$", intersectionpoint(m, line(b,c)), align=SW);
label("$E$", intersectionpoint(n, line(b,a)) + (-0.3, 0.2), align=W);
