settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(6cm);

pair a = (0, 1.5);
pair b = (-1, 0);
pair c = (1, 0);

show(triangle(a,b,c), La="", Lb="", Lc="");
circle i = incircle(triangle(a,b,c));
draw(i);
pair c1[] = intersectionpoints(i, line(a, b));
line p1 = perpendicular(c1[0], line(a,b));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[0]);
pair p2 = intersectionpoint(t1, line(b, c));
pair p3 = intersectionpoint(t1, line(a, c));
draw(p2 -- p3);
markangle("$B$", radius=10, c,b,a);
markangle("$A$", radius=10, b,a,c);
markangle("$C$", radius=10, a,c,b);
markangle("$B$", radius=10, c,p2,p3);
markangle("$A$", radius=10, p2,p3,c);
label("$T$", p2, align=S);
label("$U$", p3, align=E);
pair c1[] = intersectionpoints(i, line(b, c));
line p1 = perpendicular(c1[0], line(b,c));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[1]);
pair p2 = intersectionpoint(t1, line(a, b));
pair p3 = intersectionpoint(t1, line(a, c));
markangle("$B$", radius=10, p3,p2,a);
markangle("$C$", radius=10, a,p3,p2);
label("$P$", p2, align=W);
label("$Q$", p3, align=E);
draw(p2 -- p3);
pair c1[] = intersectionpoints(i, line(a, c));
line p1 = perpendicular(c1[0], line(a,c));
pair c2[] = intersectionpoints(i, p1);
line t1 = tangent(i, c2[0]);
pair p2 = intersectionpoint(t1, line(a, b));
pair p3 = intersectionpoint(t1, line(b, c));
draw(p2 -- p3);
markangle("$A$", radius=10, b,p2,p3);
markangle("$C$", radius=10, p2,p3,b);
label("$R$", p2, align=W);
label("$S$", p3, align=S);
