settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(6cm);

pair a = (0,3);
pair b = (-2,0);
pair c = (2,0);
triangle t = triangle(a,b,c);
show(t);
pair i = incenter(t);
draw(b -- i);
pair h = midpoint(line(b, i));
pair h = h + (.3, (i.y - b.y)/(i.x - b.x)*.3);
line l = perpendicular(h, line(b, c));
real r = distance(line(b, c), h);
draw(circle(h, r));
line m = perpendicular(i, line(a, b));
draw(i -- intersectionpoint(m, line(a,b)));
line n = perpendicular(i, line(c, b));
pair p = intersectionpoint(n, line(b, c));
draw(i -- p);
line l1 = perpendicular(h, line(i, p));
draw(h -- intersectionpoint(l1, line(i, p)));
line m1 = perpendicular(h, line(b, c));
draw(h -- intersectionpoint(m1, line(b, c)));
label("$L$", intersectionpoint(l1, line(i, p)), align=E);
label("$K$", intersectionpoint(m1, line(b, c)), align=S);
label("$H$", h, align=NW);
label("$I$", i, align=NE);
label("$D$", intersectionpoint(n, line(b, c)), align=SE);
markangle("$B/2$", radius=10, c, b, i);
markangle("$B/2$", radius=10, intersectionpoint(l1, line(i, p)), h, i);
