settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(6cm);

pair a = (0,3);
pair b = (-2,0);
pair c = (3,0);
triangle t = triangle(a,b,c);
show(La="", t);
pair o = orthocentercenter(t);
pair cc = circumcenter(t);
draw(cc -- a);
draw(cc -- b);
draw(cc -- c);
draw(o -- a);
line l = line(o, a);
line m = line(o, cc);
pair p1 = intersectionpoint(l, line(b,c));
pair p2 = intersectionpoint(m, line(b,c));
draw(a -- p1);
draw(o -- p2);
label("$D$", p1, align=S);
label("$Q$", p2, align=SE);
label("$O$", cc, align=NE);
label("$P$", o, align=NW);
line l1 = perpendicular(cc, l);
line m1 = perpendicular(cc, line(b,c));
draw(cc -- intersectionpoint(l1, l));
draw(cc -- intersectionpoint(m1, line(b,c)));
label("$M$", intersectionpoint(l1, l), align=W);
label("$F$", intersectionpoint(m1, line(b,c)), align=S);
markangle("$\theta$", radius=10, cc, p2, b);
markangle("$\theta$", radius=10, o, cc, intersectionpoint(l1, l));
