settings.outformat = "pdf";
defaultpen(fontsize(10pt));
import geometry;

size(6cm);

pair a = (0,3);
pair b = (-2,0);
pair c = (3,0);
triangle t = triangle(a,b,c);
show(La="", Lb="", Lc="", t);
pair o = circumcenter(t);
pair i = incenter(t);
path cc = circle(t);
draw(cc);
draw(o -- b);
draw(o -- c);
line l = perpendicular(i, line(b,c));
draw(i -- intersectionpoint(l, line(b,c)));
pair p[] = intersectionpoints(l, cc);
pair j = intersectionpoint(l, line(b,c));
real d = sqrt((j.x - p[1].x)*(j.x - p[1].x) + (j.y - p[1].y)*(j.y - p[1].y));
pair q = midpoint(line(j, p[1]));
circle cd = circle(midpoint(line(j, p[1])), d/2);
draw(cd);
draw(i -- q);
draw(o -- q);
line m = line(o, q);
pair p1[] = intersectionpoints(m, cd);
draw(o -- p1[0]);
draw(o -- p1[1]);
draw(o -- (o.x, q.y));
draw(q -- (o.x, q.y));
label("$O$", o, align=N);
label("$I$", i, align=N);
label("$D$", j, align=NE);
label("$P$", q, align=SE);
label("$Q$", p1[0], align=S);
label("$N$", (o.x, q.y), align=SE);
label("$M$", intersectionpoint(line(o, (o.x, q.y)), line(b,c)), align=NE);
label("$x$", midpoint(line(j,q))+(-.1, 0));
label("$x$", midpoint(line(q, p1[0]))+(-.1, 0));
